# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to S3

on:
  push:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        check-latest: true
    - run: npm install
    - shell: bash
      env:
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        GATSBY_CACTUS_CHAT_SITE_NAME: ${{ secrets.CACTUS_CHAT_SITE_NAME }}
      run: npm run build-fresh
    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - run: npm run deploy
